apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-frontend-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: portfolio-frontend.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-frontend-svc
                port:
                  number: 80